
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.20.1
    helm:
      releaseName: vault
      values: |
        global:
          openshift: true
        injector:
          enabled: true
        server:
          dev:
            enabled: true
          serviceAccount:
            create: true
            name: vault-sa
        authDelegator:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
---
